import { Resource } from "../models/index.js";

const curatedResources = [
  {
    title: "Box Breathing for Exam Stress",
    type: "video",
    category: "Stress",
    language: "English",
    url: "https://www.youtube.com/watch?v=tEmt1Znux58",
    description: "A short guided breathing video for acute stress and study pressure.",
    durationMin: 4,
    tags: ["breathing", "exam stress", "grounding"],
  },
  {
    title: "Mindfulness Practice for Focus",
    type: "video",
    category: "Meditation",
    language: "English",
    url: "https://www.youtube.com/watch?v=inpok4MKVLM",
    description: "A simple mindfulness practice for grounding and focus.",
    durationMin: 10,
    tags: ["mindfulness", "meditation", "focus"],
  },
  {
    title: "Caring for Your Mental Health",
    type: "article",
    category: "General",
    language: "English",
    url: "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",
    description: "Self-care basics for emotional wellbeing, stress, sleep, connection, and getting help.",
    durationMin: 8,
    tags: ["self care", "wellbeing", "mental health"],
  },
  {
    title: "My Mental Health: Do I Need Help?",
    type: "article",
    category: "Support",
    language: "English",
    url: "https://www.nimh.nih.gov/health/publications/my-mental-health-do-i-need-help",
    description: "A practical guide to understand when symptoms may need professional support.",
    durationMin: 7,
    tags: ["support", "symptoms", "help"],
  },
  {
    title: "Sleep Hygiene Checklist",
    type: "article",
    category: "Sleep",
    language: "English",
    url: "https://www.sleepfoundation.org/sleep-hygiene",
    description: "Practical habits that support better sleep and recovery.",
    durationMin: 8,
    tags: ["sleep hygiene", "routine", "rest"],
  },
  {
    title: "Self-Motivation Guide",
    type: "article",
    category: "Motivation",
    language: "English",
    url: "https://www.mindtools.com/c4chclh/self-motivation",
    description: "Motivation tools for goals, confidence, positive thinking, and personal growth.",
    durationMin: 9,
    tags: ["motivation", "goals", "confidence"],
  },
  {
    title: "How to Build Self-Confidence",
    type: "article",
    category: "Self Confidence",
    language: "English",
    url: "https://www.mindtools.com/ap5omwt/how-to-build-self-confidence/",
    description: "Practical steps for improving confidence, self-belief, and daily performance.",
    durationMin: 10,
    tags: ["self confidence", "motivation", "growth"],
  },
  {
    title: "Understanding Anxiety Disorders",
    type: "article",
    category: "Anxiety",
    language: "English",
    url: "https://www.nimh.nih.gov/health/topics/anxiety-disorders",
    description: "Reliable information about anxiety symptoms, support options, and treatment paths.",
    durationMin: 9,
    tags: ["anxiety", "symptoms", "support"],
  },
  {
    title: "Depression Information and Support",
    type: "article",
    category: "Depression",
    language: "English",
    url: "https://www.nimh.nih.gov/health/topics/depression",
    description: "Trusted guidance about depression signs, treatment, and when to seek help.",
    durationMin: 9,
    tags: ["depression", "support", "mental health"],
  },
  {
    title: "Coping With Traumatic Stress Reactions",
    type: "article",
    category: "Trauma Support",
    language: "English",
    url: "https://www.ptsd.va.gov/gethelp/coping_stress_reactions.asp",
    description: "Grounding, breathing, and active coping ideas for traumatic stress reactions.",
    durationMin: 12,
    tags: ["trauma support", "grounding", "coping"],
  },
  {
    title: "Recovery and Recovery Support",
    type: "article",
    category: "Addiction Recovery",
    language: "English",
    url: "https://www.samhsa.gov/find-help/recovery",
    description: "Recovery support principles for people working through substance use challenges.",
    durationMin: 8,
    tags: ["addiction recovery", "support", "recovery"],
  },
  {
    title: "Managing Student Stress",
    type: "article",
    category: "Student Pressure",
    language: "English",
    url: "https://jedfoundation.org/resource/how-to-manage-stress/",
    description: "Student-friendly stress management strategies for school, exams, and pressure.",
    durationMin: 8,
    tags: ["student pressure", "exam stress", "study"],
  },
  {
    title: "Stress Management Strategies",
    type: "article",
    category: "Stress",
    language: "English",
    url: "https://www.helpguide.org/mental-health/stress/stress-management",
    description: "Healthy strategies for reducing stress and building resilience.",
    durationMin: 12,
    tags: ["stress", "resilience", "coping"],
  },
  {
    title: "Burnout Recovery Tips",
    type: "article",
    category: "Burnout",
    language: "English",
    url: "https://www.helpguide.org/mental-health/stress/burnout-prevention-and-recovery",
    description: "How to recognize burnout and rebuild energy with boundaries and support.",
    durationMin: 11,
    tags: ["burnout", "boundaries", "recovery"],
  },
  {
    title: "Healthy Boundaries in Relationships",
    type: "article",
    category: "Relationships",
    language: "English",
    url: "https://www.helpguide.org/articles/relationships-communication/setting-healthy-boundaries-in-relationships.htm",
    description: "A guide to setting boundaries that protect identity, wellbeing, and relationships.",
    durationMin: 10,
    tags: ["relationships", "boundaries", "communication"],
  },
  {
    title: "Dealing With Loneliness",
    type: "article",
    category: "Loneliness",
    language: "English",
    url: "https://www.helpguide.org/relationships/social-connection/loneliness-and-social-isolation",
    description: "Ways to rebuild connection and reduce loneliness or social isolation.",
    durationMin: 9,
    tags: ["loneliness", "connection", "support"],
  },
  {
    title: "Relaxation Techniques for Stress Relief",
    type: "article",
    category: "Meditation",
    language: "English",
    url: "https://www.helpguide.org/mental-health/stress/relaxation-techniques-for-stress-relief",
    description: "Relaxation practices for calming the body and easing stress.",
    durationMin: 10,
    tags: ["relaxation", "breathing", "meditation"],
  },
];

async function seedDatabase() {
  await Resource.deleteMany({ type: "audio" });

  for (const resource of curatedResources) {
    await Resource.updateOne(
      { title: resource.title },
      {
        $set: resource,
        $setOnInsert: { createdAt: new Date() },
      },
      { upsert: true }
    );
  }
}

export { seedDatabase };
