import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import { CounsellorApplication, Resource, User } from "../models/index.js";

const curatedResources = [
  {
    title: "Box Breathing for Exam Stress",
    type: "video",
    category: "Stress",
    language: "English",
    url: "https://www.youtube.com/watch?v=tEmt1Znux58",
    description: "A short guided breathing video for acute stress and study pressure.",
    durationMin: 4,
    tags: ["breathing", "exam stress", "grounding"],
  },
  {
    title: "Mindfulness Practice for Focus",
    type: "video",
    category: "Meditation",
    language: "English",
    url: "https://www.youtube.com/watch?v=inpok4MKVLM",
    description: "A simple mindfulness practice for grounding and focus.",
    durationMin: 10,
    tags: ["mindfulness", "meditation", "focus"],
  },
  {
    title: "Caring for Your Mental Health",
    type: "article",
    category: "General",
    language: "English",
    url: "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",
    description: "Self-care basics for emotional wellbeing, stress, sleep, connection, and getting help.",
    durationMin: 8,
    tags: ["self care", "wellbeing", "mental health"],
  },
  {
    title: "My Mental Health: Do I Need Help?",
    type: "article",
    category: "Support",
    language: "English",
    url: "https://www.nimh.nih.gov/health/publications/my-mental-health-do-i-need-help",
    description: "A practical guide to understand when symptoms may need professional support.",
    durationMin: 7,
    tags: ["support", "symptoms", "help"],
  },
  {
    title: "Sleep Hygiene Checklist",
    type: "article",
    category: "Sleep",
    language: "English",
    url: "https://www.sleepfoundation.org/sleep-hygiene",
    description: "Practical habits that support better sleep and recovery.",
    durationMin: 8,
    tags: ["sleep hygiene", "routine", "rest"],
  },
  {
    title: "Self-Motivation Guide",
    type: "article",
    category: "Motivation",
    language: "English",
    url: "https://www.mindtools.com/c4chclh/self-motivation",
    description: "Motivation tools for goals, confidence, positive thinking, and personal growth.",
    durationMin: 9,
    tags: ["motivation", "goals", "confidence"],
  },
  {
    title: "How to Build Self-Confidence",
    type: "article",
    category: "Self Confidence",
    language: "English",
    url: "https://www.mindtools.com/ap5omwt/how-to-build-self-confidence/",
    description: "Practical steps for improving confidence, self-belief, and daily performance.",
    durationMin: 10,
    tags: ["self confidence", "motivation", "growth"],
  },
  {
    title: "Understanding Anxiety Disorders",
    type: "article",
    category: "Anxiety",
    language: "English",
    url: "https://www.nimh.nih.gov/health/topics/anxiety-disorders",
    description: "Reliable information about anxiety symptoms, support options, and treatment paths.",
    durationMin: 9,
    tags: ["anxiety", "symptoms", "support"],
  },
  {
    title: "Depression Information and Support",
    type: "article",
    category: "Depression",
    language: "English",
    url: "https://www.nimh.nih.gov/health/topics/depression",
    description: "Trusted guidance about depression signs, treatment, and when to seek help.",
    durationMin: 9,
    tags: ["depression", "support", "mental health"],
  },
  {
    title: "Coping With Traumatic Stress Reactions",
    type: "article",
    category: "Trauma Support",
    language: "English",
    url: "https://www.ptsd.va.gov/gethelp/coping_stress_reactions.asp",
    description: "Grounding, breathing, and active coping ideas for traumatic stress reactions.",
    durationMin: 12,
    tags: ["trauma support", "grounding", "coping"],
  },
  {
    title: "Recovery and Recovery Support",
    type: "article",
    category: "Addiction Recovery",
    language: "English",
    url: "https://www.samhsa.gov/find-help/recovery",
    description: "Recovery support principles for people working through substance use challenges.",
    durationMin: 8,
    tags: ["addiction recovery", "support", "recovery"],
  },
  {
    title: "Managing Student Stress",
    type: "article",
    category: "Student Pressure",
    language: "English",
    url: "https://jedfoundation.org/resource/how-to-manage-stress/",
    description: "Student-friendly stress management strategies for school, exams, and pressure.",
    durationMin: 8,
    tags: ["student pressure", "exam stress", "study"],
  },
  {
    title: "Stress Management Strategies",
    type: "article",
    category: "Stress",
    language: "English",
    url: "https://www.helpguide.org/mental-health/stress/stress-management",
    description: "Healthy strategies for reducing stress and building resilience.",
    durationMin: 12,
    tags: ["stress", "resilience", "coping"],
  },
  {
    title: "Burnout Recovery Tips",
    type: "article",
    category: "Burnout",
    language: "English",
    url: "https://www.helpguide.org/mental-health/stress/burnout-prevention-and-recovery",
    description: "How to recognize burnout and rebuild energy with boundaries and support.",
    durationMin: 11,
    tags: ["burnout", "boundaries", "recovery"],
  },
  {
    title: "Healthy Boundaries in Relationships",
    type: "article",
    category: "Relationships",
    language: "English",
    url: "https://www.helpguide.org/articles/relationships-communication/setting-healthy-boundaries-in-relationships.htm",
    description: "A guide to setting boundaries that protect identity, wellbeing, and relationships.",
    durationMin: 10,
    tags: ["relationships", "boundaries", "communication"],
  },
  {
    title: "Dealing With Loneliness",
    type: "article",
    category: "Loneliness",
    language: "English",
    url: "https://www.helpguide.org/relationships/social-connection/loneliness-and-social-isolation",
    description: "Ways to rebuild connection and reduce loneliness or social isolation.",
    durationMin: 9,
    tags: ["loneliness", "connection", "support"],
  },
  {
    title: "Relaxation Techniques for Stress Relief",
    type: "article",
    category: "Meditation",
    language: "English",
    url: "https://www.helpguide.org/mental-health/stress/relaxation-techniques-for-stress-relief",
    description: "Relaxation practices for calming the body and easing stress.",
    durationMin: 10,
    tags: ["relaxation", "breathing", "meditation"],
  },
];

const seededCounsellors = [
  {
    name: "Dr. Aisha Mehra",
    email: "aisha.mehra@mindsupport.seed",
    specialization: "Anxiety and Stress Management",
    bio: "Licensed psychologist helping students manage anxiety, panic, exam stress, and emotional overwhelm with practical coping plans.",
    counsellorType: "professional",
    verificationBadge: "Verified Professional",
    experience: "8 years",
    languages: ["English", "Hindi"],
    sessionPricing: 900,
    categories: ["Anxiety", "Stress", "Student Pressure"],
    availability: ["Mon 10:00-13:00", "Wed 15:00-18:00", "Fri 11:00-14:00"],
    rating: 4.9,
    reviews: 128,
    responseTime: "Fast Response",
    licenseNumber: "MHP-PSY-1001",
    certificateLinks: ["https://example.com/certificates/aisha-mehra"],
    linkedin: "https://www.linkedin.com/in/aisha-mehra",
  },
  {
    name: "Rahul Verma",
    email: "rahul.verma@mindsupport.seed",
    specialization: "Career Pressure and Confidence",
    bio: "Community mentor focused on career stress, self-confidence, interview pressure, and small-step motivation for students.",
    counsellorType: "mentor",
    verificationBadge: "Community Mentor",
    experience: "5 years",
    languages: ["English", "Hindi", "Marathi"],
    sessionPricing: 450,
    categories: ["Career Stress", "Self Confidence", "Motivation"],
    availability: ["Tue 18:00-21:00", "Thu 18:00-21:00", "Sat 10:00-13:00"],
    rating: 4.7,
    reviews: 86,
    responseTime: "Within 12 hours",
    linkedin: "https://www.linkedin.com/in/rahul-verma",
  },
  {
    name: "Dr. Neha Iyer",
    email: "neha.iyer@mindsupport.seed",
    specialization: "Depression and Mood Support",
    bio: "Professional counsellor supporting low mood, loneliness, grief, emotional numbness, and therapy progress tracking.",
    counsellorType: "professional",
    verificationBadge: "Verified Professional",
    experience: "10 years",
    languages: ["English", "Tamil"],
    sessionPricing: 1100,
    categories: ["Depression", "Loneliness", "General"],
    availability: ["Mon 16:00-19:00", "Thu 10:00-13:00", "Sat 14:00-17:00"],
    rating: 4.8,
    reviews: 142,
    responseTime: "Fast Response",
    licenseNumber: "MHP-PSY-1002",
    certificateLinks: ["https://example.com/certificates/neha-iyer"],
    linkedin: "https://www.linkedin.com/in/neha-iyer",
  },
  {
    name: "Kabir Khan",
    email: "kabir.khan@mindsupport.seed",
    specialization: "Addiction Recovery Peer Support",
    bio: "Peer support mentor for recovery routines, relapse prevention habits, accountability, and rebuilding confidence.",
    counsellorType: "mentor",
    verificationBadge: "Community Mentor",
    experience: "6 years",
    languages: ["English", "Hindi", "Urdu"],
    sessionPricing: 400,
    categories: ["Addiction Recovery", "Stress", "Motivation"],
    availability: ["Wed 18:00-21:00", "Fri 18:00-21:00", "Sun 11:00-14:00"],
    rating: 4.6,
    reviews: 74,
    responseTime: "Within 24 hours",
    linkedin: "https://www.linkedin.com/in/kabir-khan",
  },
  {
    name: "Dr. Priya Nair",
    email: "priya.nair@mindsupport.seed",
    specialization: "Trauma Support and Grounding",
    bio: "Trauma-informed therapist helping clients with grounding, safety planning, triggers, PTSD symptoms, and emotional regulation.",
    counsellorType: "professional",
    verificationBadge: "Verified Professional",
    experience: "12 years",
    languages: ["English", "Malayalam", "Hindi"],
    sessionPricing: 1300,
    categories: ["Trauma Support", "PTSD", "Anxiety"],
    availability: ["Tue 09:00-12:00", "Thu 14:00-17:00", "Sat 09:00-12:00"],
    rating: 4.9,
    reviews: 166,
    responseTime: "Fast Response",
    licenseNumber: "MHP-PSY-1003",
    certificateLinks: ["https://example.com/certificates/priya-nair"],
    linkedin: "https://www.linkedin.com/in/priya-nair",
  },
  {
    name: "Sana Qureshi",
    email: "sana.qureshi@mindsupport.seed",
    specialization: "Relationship and Breakup Recovery",
    bio: "Community mentor supporting breakup recovery, relationship boundaries, loneliness, and rebuilding daily stability.",
    counsellorType: "mentor",
    verificationBadge: "Community Mentor",
    experience: "4 years",
    languages: ["English", "Hindi"],
    sessionPricing: 350,
    categories: ["Relationships", "Loneliness", "Self Confidence"],
    availability: ["Mon 19:00-21:00", "Wed 19:00-21:00", "Sun 16:00-19:00"],
    rating: 4.7,
    reviews: 63,
    responseTime: "Within 12 hours",
    linkedin: "https://www.linkedin.com/in/sana-qureshi",
  },
  {
    name: "Dr. Arjun Sen",
    email: "arjun.sen@mindsupport.seed",
    specialization: "Sleep, Burnout and Workload Balance",
    bio: "Professional psychologist helping students and early professionals with burnout, sleep routines, stress recovery, and boundaries.",
    counsellorType: "professional",
    verificationBadge: "Verified Professional",
    experience: "9 years",
    languages: ["English", "Bengali", "Hindi"],
    sessionPricing: 1000,
    categories: ["Sleep", "Burnout", "Career Stress"],
    availability: ["Tue 13:00-16:00", "Fri 10:00-13:00", "Sat 12:00-15:00"],
    rating: 4.8,
    reviews: 119,
    responseTime: "Fast Response",
    licenseNumber: "MHP-PSY-1004",
    certificateLinks: ["https://example.com/certificates/arjun-sen"],
    linkedin: "https://www.linkedin.com/in/arjun-sen",
  },
  {
    name: "Meera Shah",
    email: "meera.shah@mindsupport.seed",
    specialization: "Meditation and Emotional Balance",
    bio: "Mindfulness mentor teaching simple meditation, breathing routines, gratitude practice, and calm daily habits.",
    counsellorType: "mentor",
    verificationBadge: "Community Mentor",
    experience: "7 years",
    languages: ["English", "Gujarati", "Hindi"],
    sessionPricing: 500,
    categories: ["Meditation", "Stress", "General"],
    availability: ["Mon 07:00-09:00", "Wed 07:00-09:00", "Sat 08:00-11:00"],
    rating: 4.8,
    reviews: 91,
    responseTime: "Within 24 hours",
    linkedin: "https://www.linkedin.com/in/meera-shah",
  },
];

async function seedDatabase() {
  await Resource.deleteMany({ type: "audio" });

  for (const resource of curatedResources) {
    await Resource.updateOne(
      { title: resource.title },
      {
        $set: resource,
        $setOnInsert: { createdAt: new Date() },
      },
      { upsert: true }
    );
  }

  for (const counsellor of seededCounsellors) {
    const passwordHash = await bcrypt.hash(crypto.randomUUID(), 12);
    const userUpdate = {
      ...counsellor,
      role: "counsellor",
      status: "approved",
      verificationStatus: "approved",
      otpVerified: true,
      otpVerifiedAt: new Date(),
      platformCommission: 15,
      meetLink: "https://meet.google.com/new",
      profilePhotoUrl: `https://ui-avatars.com/api/?name=${encodeURIComponent(counsellor.name)}&background=8b5cf6&color=fff`,
      idVerification: "Seed verification record",
    };
    await User.updateOne(
      { email: counsellor.email },
      {
        $set: userUpdate,
        $setOnInsert: { passwordHash, createdAt: new Date() },
      },
      { upsert: true }
    );
    const user = await User.findOne({ email: counsellor.email });
    await CounsellorApplication.updateOne(
      { user: user._id },
      {
        $set: {
          user: user._id,
          status: "approved",
          requestedType: counsellor.counsellorType,
          fullName: counsellor.name,
          bio: counsellor.bio,
          specialization: counsellor.specialization,
          experience: counsellor.experience,
          languages: counsellor.languages,
          sessionPricing: counsellor.sessionPricing,
          profilePhotoUrl: userUpdate.profilePhotoUrl,
          certificateLinks: counsellor.certificateLinks || [],
          linkedin: counsellor.linkedin || "",
          idDocumentType: "Seed Verification",
          idDocumentNumber: "SEED-APPROVED",
          licenseNumber: counsellor.licenseNumber || "",
          education: counsellor.counsellorType === "professional" ? "Verified professional qualification" : "Peer support training",
          categories: counsellor.categories,
          availability: counsellor.availability,
          approach: "Warm, structured, privacy-first support.",
          emergencyTraining: "Crisis escalation and safety referral basics",
          referenceContact: "platform-seed@mindsupport.local",
          verificationNotes: "Seeded approved counsellor for marketplace launch data.",
          reviewedAt: new Date(),
        },
        $setOnInsert: { createdAt: new Date() },
      },
      { upsert: true }
    );
  }
}

export { seedDatabase };
